function createPublicBridge(ipcRenderer) {
  function listener(channel, handler) {
    const wrapped = (_event, payload) => handler(payload);
    ipcRenderer.on(channel, wrapped);
    return () => ipcRenderer.removeListener(channel, wrapped);
  }
  return {
  getState: () => ipcRenderer.invoke('app:get-state'),
  completeOnboarding: (payload) => ipcRenderer.invoke('onboarding:complete', payload),
  pingServer: () => ipcRenderer.invoke('server:ping'),
  copyServerAddress: () => ipcRenderer.invoke('server:copy-address'),
  checkPack: () => ipcRenderer.invoke('pack:check'),
  updatePack: (force = false) => ipcRenderer.invoke('pack:update', force),
  repairPack: () => ipcRenderer.invoke('pack:repair'),
  listMods: () => ipcRenderer.invoke('mods:list'),
  addMods: () => ipcRenderer.invoke('mods:add'),
  toggleMod: (filename) => ipcRenderer.invoke('mods:toggle', filename),
  removeMod: (filename) => ipcRenderer.invoke('mods:remove', filename),
  favoriteMod: (filename) => ipcRenderer.invoke('mods:favorite', filename),
  pinMod: (filename) => ipcRenderer.invoke('mods:pin', filename),
  setAllUserModsEnabled: (enabled) => ipcRenderer.invoke('mods:set-all-enabled', enabled),
  auditMods: () => ipcRenderer.invoke('mods:audit'),
  modChangeHistory: (limit) => ipcRenderer.invoke('mods:history', limit),
  crashGuard: () => ipcRenderer.invoke('diagnostic:crash-guard'),
  disableCrashSuspects: (filenames) => ipcRenderer.invoke('diagnostic:disable-suspects', filenames),
  listRecoveryPoints: () => ipcRenderer.invoke('recovery:list'),
  createRecoveryPoint: (label) => ipcRenderer.invoke('recovery:create', label),
  restoreRecoveryPoint: (id) => ipcRenderer.invoke('recovery:restore', id),
  deleteRecoveryPoint: (id) => ipcRenderer.invoke('recovery:delete', id),
  healthCheck: () => ipcRenderer.invoke('app:health-check'),
  installJava: () => ipcRenderer.invoke('java:install'),
  resetGamePreset: (preset) => ipcRenderer.invoke('game:preset-reset', preset),
  checkPlayUpdate: () => ipcRenderer.invoke('game:play-check'),
  launchGame: () => ipcRenderer.invoke('game:launch'),
  updateAndLaunch: () => ipcRenderer.invoke('game:update-launch'),
  launchSafeGame: () => ipcRenderer.invoke('game:safe-launch'),
  buildDiagnostic: () => ipcRenderer.invoke('diagnostic:build'),
  quickDiagnostic: () => ipcRenderer.invoke('diagnostic:quick'),
  copyDiagnostic: () => ipcRenderer.invoke('diagnostic:copy'),
  saveDiagnostic: () => ipcRenderer.invoke('diagnostic:save'),
  exportSupportBundle: () => ipcRenderer.invoke('diagnostic:bundle'),
  saveSettings: (patch) => ipcRenderer.invoke('settings:save', patch),
  exportSettings: () => ipcRenderer.invoke('settings:export'),
  importSettings: () => ipcRenderer.invoke('settings:import'),
  clearPackCache: () => ipcRenderer.invoke('storage:cache-clear'),
  getStorageSummary: () => ipcRenderer.invoke('storage:summary'),
  cleanupLogs: (days) => ipcRenderer.invoke('storage:cleanup-logs', days),
  vaultStatus: () => ipcRenderer.invoke('vault:status'),
  chooseVaultDirectory: () => ipcRenderer.invoke('vault:choose'),
  pushVault: () => ipcRenderer.invoke('vault:push'),
  pullVault: (force = false) => ipcRenderer.invoke('vault:pull', force),
  connectivityCheck: () => ipcRenderer.invoke('app:connectivity'),
  accountStatus: () => ipcRenderer.invoke('account:status'),
  accountLogin: () => ipcRenderer.invoke('account:login'),
  accountLogout: () => ipcRenderer.invoke('account:logout'),
  accountRefresh: () => ipcRenderer.invoke('account:refresh'),
  accountSkins: () => ipcRenderer.invoke('account:skins'),
  accountUploadSkin: (variant) => ipcRenderer.invoke('account:upload-skin', variant),
  chooseSkinFile: () => ipcRenderer.invoke('account:choose-skin'),
  clipsList: () => ipcRenderer.invoke('clips:list'),
  clipsChooseFolder: () => ipcRenderer.invoke('clips:choose-folder'),
  clipsOpenFolder: () => ipcRenderer.invoke('clips:open-folder'),
  clipsOpen: (file) => ipcRenderer.invoke('clips:open', file),
  clipsClearFolder: () => ipcRenderer.invoke('clips:clear-folder'),
  chooseInstallDirectory: () => ipcRenderer.invoke('settings:choose-install-dir'),
  checkLauncherUpdate: () => ipcRenderer.invoke('launcher:update-check'),
  downloadLauncherUpdate: () => ipcRenderer.invoke('launcher:update-download'),
  cancelLauncherUpdate: () => ipcRenderer.invoke('launcher:update-cancel'),
  installLauncherUpdate: () => ipcRenderer.invoke('launcher:update-install'),
  openInstance: () => ipcRenderer.invoke('shell:open-instance'),
  openLogs: () => ipcRenderer.invoke('shell:open-logs'),
  openLatestLog: () => ipcRenderer.invoke('shell:open-latest-log'),
  openExternal: (url) => ipcRenderer.invoke('shell:open-external', url),
  minimize: () => ipcRenderer.send('window:minimize'),
  toggleMaximize: () => ipcRenderer.send('window:maximize-toggle'),
  close: () => ipcRenderer.send('window:close'),
  onPackProgress: (handler) => listener('pack:progress', handler),
  onGameLog: (handler) => listener('game:log', handler),
  onGameExit: (handler) => listener('game:exit', handler),
  onMaximized: (handler) => listener('window:maximized', handler),
  onLauncherUpdate: (handler) => listener('launcher:update-event', handler),
  onWindowVisibility: (handler) => listener('window:visibility', handler),
  onUiCommand: (handler) => listener('ui:command', handler)
  };
}

module.exports = { createPublicBridge };
