const { contextBridge, ipcRenderer } = require('electron');

function listener(channel, handler) {
  const wrapped = (_event, payload) => handler(payload);
  ipcRenderer.on(channel, wrapped);
  return () => ipcRenderer.removeListener(channel, wrapped);
}

contextBridge.exposeInMainWorld('eternal', {
  getState: () => ipcRenderer.invoke('app:get-state'),
  completeOnboarding: (payload) => ipcRenderer.invoke('onboarding:complete', payload),
  pingServer: () => ipcRenderer.invoke('server:ping'),
  copyServerAddress: () => ipcRenderer.invoke('server:copy-address'),
  checkPack: () => ipcRenderer.invoke('pack:check'),
  updatePack: (force = false) => ipcRenderer.invoke('pack:update', force),
  repairPack: () => ipcRenderer.invoke('pack:repair'),
  listMods: () => ipcRenderer.invoke('mods:list'),
  addMods: () => ipcRenderer.invoke('mods:add'),
  toggleMod: (filename) => ipcRenderer.invoke('mods:toggle', filename),
  removeMod: (filename) => ipcRenderer.invoke('mods:remove', filename),
  favoriteMod: (filename) => ipcRenderer.invoke('mods:favorite', filename),
  pinMod: (filename) => ipcRenderer.invoke('mods:pin', filename),
  setAllUserModsEnabled: (enabled) => ipcRenderer.invoke('mods:set-all-enabled', enabled),
  searchMods: (payload) => ipcRenderer.invoke('mods:search', payload),
  planModInstall: (project) => ipcRenderer.invoke('mods:plan', project),
  installMod: (project) => ipcRenderer.invoke('mods:install', project),
  getModDetails: (project) => ipcRenderer.invoke('mods:details', project),
  identifyLocalMods: () => ipcRenderer.invoke('mods:identify-local'),
  checkModUpdates: () => ipcRenderer.invoke('mods:updates-check'),
  updateMod: (filename) => ipcRenderer.invoke('mods:update-one', filename),
  updateAllMods: () => ipcRenderer.invoke('mods:update-all'),
  auditMods: () => ipcRenderer.invoke('mods:audit'),
  modChangeHistory: (limit) => ipcRenderer.invoke('mods:history', limit),
  crashGuard: () => ipcRenderer.invoke('diagnostic:crash-guard'),
  disableCrashSuspects: (filenames) => ipcRenderer.invoke('diagnostic:disable-suspects', filenames),
  listRecoveryPoints: () => ipcRenderer.invoke('recovery:list'),
  createRecoveryPoint: (label) => ipcRenderer.invoke('recovery:create', label),
  restoreRecoveryPoint: (id) => ipcRenderer.invoke('recovery:restore', id),
  deleteRecoveryPoint: (id) => ipcRenderer.invoke('recovery:delete', id),
  healthCheck: () => ipcRenderer.invoke('app:health-check'),
  installJava: () => ipcRenderer.invoke('java:install'),
  resetGamePreset: (preset) => ipcRenderer.invoke('game:preset-reset', preset),
  launchGame: () => ipcRenderer.invoke('game:launch'),
  launchSafeGame: () => ipcRenderer.invoke('game:safe-launch'),
  buildDiagnostic: () => ipcRenderer.invoke('diagnostic:build'),
  quickDiagnostic: () => ipcRenderer.invoke('diagnostic:quick'),
  copyDiagnostic: () => ipcRenderer.invoke('diagnostic:copy'),
  saveDiagnostic: () => ipcRenderer.invoke('diagnostic:save'),
  exportSupportBundle: () => ipcRenderer.invoke('diagnostic:bundle'),
  saveSettings: (patch) => ipcRenderer.invoke('settings:save', patch),
  exportSettings: () => ipcRenderer.invoke('settings:export'),
  importSettings: () => ipcRenderer.invoke('settings:import'),
  clearPackCache: () => ipcRenderer.invoke('storage:cache-clear'),
  getStorageSummary: () => ipcRenderer.invoke('storage:summary'),
  cleanupLogs: (days) => ipcRenderer.invoke('storage:cleanup-logs', days),
  vaultStatus: () => ipcRenderer.invoke('vault:status'),
  chooseVaultDirectory: () => ipcRenderer.invoke('vault:choose'),
  pushVault: () => ipcRenderer.invoke('vault:push'),
  pullVault: (force = false) => ipcRenderer.invoke('vault:pull', force),
  connectivityCheck: () => ipcRenderer.invoke('app:connectivity'),
  accountStatus: () => ipcRenderer.invoke('account:status'),
  accountLogin: () => ipcRenderer.invoke('account:login'),
  accountLogout: () => ipcRenderer.invoke('account:logout'),
  chooseInstallDirectory: () => ipcRenderer.invoke('settings:choose-install-dir'),
  developerStatus: () => ipcRenderer.invoke('developer:status'),
  developerPreflight: () => ipcRenderer.invoke('developer:preflight'),
  developerBackupSource: () => ipcRenderer.invoke('developer:backup-source'),
  developerSetup: (password) => ipcRenderer.invoke('developer:setup', password),
  developerUnlock: (password) => ipcRenderer.invoke('developer:unlock', password),
  developerResetAccess: () => ipcRenderer.invoke('developer:reset-access'),
  developerLock: () => ipcRenderer.invoke('developer:lock'),
  developerChangePassword: (payload) => ipcRenderer.invoke('developer:change-password', payload),
  developerSetCurseForgeKey: (key) => ipcRenderer.invoke('developer:set-curseforge-key', key),
  developerChooseSource: () => ipcRenderer.invoke('developer:choose-source'),
  developerChooseTest: () => ipcRenderer.invoke('developer:choose-test'),
  developerOpenTest: () => ipcRenderer.invoke('developer:open-test'),
  developerLaunchTest: () => ipcRenderer.invoke('developer:launch-test'),
  developerCopyModTest: (filename) => ipcRenderer.invoke('developer:copy-mod-test', filename),
  developerSyncTestMods: () => ipcRenderer.invoke('developer:sync-test-mods'),
  developerInstallModTest: (project) => ipcRenderer.invoke('developer:install-mod-test', project),
  developerPublish: (payload) => ipcRenderer.invoke('developer:publish', payload),
  developerPreviewPublish: (payload) => ipcRenderer.invoke('developer:publish-preview', payload),
  developerCompareTest: () => ipcRenderer.invoke('developer:test-compare'),
  developerPromoteTestMod: (filename) => ipcRenderer.invoke('developer:test-promote', filename),
  developerPromoteAllTestMods: () => ipcRenderer.invoke('developer:test-promote-all'),
  checkLauncherUpdate: () => ipcRenderer.invoke('launcher:update-check'),
  downloadLauncherUpdate: () => ipcRenderer.invoke('launcher:update-download'),
  installLauncherUpdate: () => ipcRenderer.invoke('launcher:update-install'),
  openInstance: () => ipcRenderer.invoke('shell:open-instance'),
  openLogs: () => ipcRenderer.invoke('shell:open-logs'),
  openExternal: (url) => ipcRenderer.invoke('shell:open-external', url),
  minimize: () => ipcRenderer.send('window:minimize'),
  toggleMaximize: () => ipcRenderer.send('window:maximize-toggle'),
  close: () => ipcRenderer.send('window:close'),
  onPackProgress: (handler) => listener('pack:progress', handler),
  onGameLog: (handler) => listener('game:log', handler),
  onGameExit: (handler) => listener('game:exit', handler),
  onMaximized: (handler) => listener('window:maximized', handler),
  onLauncherUpdate: (handler) => listener('launcher:update-event', handler),
  onDeveloperPublishLog: (handler) => listener('developer:publish-log', handler),
  onUiCommand: (handler) => listener('ui:command', handler)
});
